name: 'Learn workflow pm2 version'
on: [push]
jobs: 
  check-pm2-version:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v1
      with: 
        node-version: '12.x'
      run: npm install -g pm2
      run: pm2 -v



